version: '3.8'
services:
  erp_database:
    build:
      context: ./backend
      dockerfile: database.Dockerfile
    container_name: erp_database
    ports:
      - "5432:5432"
    volumes:
      - erp_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/postgres-healthcheck.sh" ]
      interval: 5s
      timeout: 5s
      retries: 5

  erp_backend:
    build:
      context: ./backend
      dockerfile: app.Dockerfile
    container_name: erp_backend
    ports:
      - "8080:8080"
    depends_on:
      erp_database:
        condition: service_healthy
    env_file:
      - ./backend/.env

  erp_web:
    build:
      context: ./frontend
      dockerfile: web.Dockerfile
      args:
        API_URL: ${API_URL}
    container_name: erp_web
    ports:
      - "4200:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - erp_backend

volumes:
  erp_data:
