services:
  erp_database:
    build:
      context: ./backend
      dockerfile: database.Dockerfile
    container_name: erp_database
    volumes:
      - erp_data:/var/lib/postgresql/data
    env_file:
      - ./backend/db.env
    healthcheck:
      test: [ "CMD-SHELL", "/usr/local/bin/postgres-healthcheck.sh" ]
      interval: 5s
      timeout: 5s
      retries: 5

  erp_backend:
    build:
      context: ./backend
      dockerfile: app.Dockerfile
    container_name: erp_backend
    volumes:
      - /var/apps/erp-crud/images:/opt/app/images/
    depends_on:
      erp_database:
        condition: service_healthy
    env_file:
      - ./backend/backend.env

  erp_web:
    build:
      context: ./frontend
      dockerfile: web.Dockerfile
      args:
        API_URL: ${API_URL}
    container_name: erp_web
    ports:
      - "80:80"
    depends_on:
      - erp_backend

  erp_flyway:
    image: flyway/flyway:10-alpine
    container_name: erp_flyway
    volumes:
      - ./backend/sql:/flyway/sql
    depends_on:
      - erp_database
    command: -url=jdbc:postgresql://erp_database:5432/${FLYWAY_DATABASE} -schemas=public -user=${FLYWAY_USER} -password=${FLYWAY_PASSWORD} -connectRetries=10 migrate

volumes:
  erp_data:
