-- Insertar domicilios
INSERT INTO domicilio_sucursal(calle, numero_calle, colonia, codigo_postal) VALUES 
('Francisco Monteverde', '517', 'Ley 57', '83100'),
('Miguel Ángel de Quevedo', '223', 'Santa María', '83110'),
('Morelos', '119', 'Guadalupe', '83120'),
('Juárez', '456', 'Centro', '83130'),
('Pino Suárez', '782', 'San Juan', '83140'),
('Hidalgo', '324', 'Santa Isabel', '83150'),
('Insurgentes', '887', 'Roma', '83160'),
('López Mateos', '132', 'Guadalajara', '83170'),
('Juárez', '5', 'Tlalpan', '83180'),
('Carranza', '665', 'Monterrey', '83190'),
('Reforma', '101', 'Polanco', '83101'),
('México', '20', 'Chimalhuacán', '83102'),
('5 de Febrero', '30', 'Querétaro', '83103'),
('Revolución', '142', 'La Condesa', '83104'),
('Calzada de la Virgen', '234', 'Iztacalco', '83105'),
('Guadalupe Victoria', '888', 'Coyoacán', '83106'),
('Paseo de la Reforma', '100', 'Juárez', '83107'),
('José María Morelos', '99', 'Mérida', '83108'),
('Lázaro Cárdenas', '55', 'Veracruz', '83109'),
('Callejón del Beso', '13', 'Guanajuato', '83111'),
('Paz', '404', 'Puebla', '83112'),
('Universidad', '256', 'San Ángel', '83113'),
('16 de Septiembre', '1', 'Tepito', '83114'),
('Xola', '200', 'Benito Juárez', '83115'),
('Abetos', '68', 'La Magdalena', '83116'),
('16 de Septiembre', '999', 'Zacatecas', '83117'),
('José de Escandon', '415', 'Ecatepec', '83118'),
('Flores', '732', 'Tlajomulco', '83119'),
('Abetos', '400', 'Querétaro', '83120'),
('Lomas de Chapultepec', '17', 'Lomas', '83121'),
('Valle de Bravo', '601', 'Naucalpan', '83122'),
('Gómez Farías', '200', 'Santiago', '83123'),
('Santa Rosa', '800', 'Hidalgo', '83124'),
('San Antonio', '123', 'San Luis Potosí', '83125'),
('Cuauhtémoc', '311', 'Nayarit', '83126'),
('Insurgentes Sur', '1500', 'San José', '83127'),
('República', '20', 'Toluca', '83128'),
('Victoria', '45', 'Durango', '83129'),
('Independencia', '34', 'Veracruz', '83130'),
('Anahuac', '301', 'Cdmx', '83131'),
('Morelos', '88', 'Colima', '83132'),
('Sol', '75', 'San Felipe', '83133'),
('Las Palmas', '12', 'Torreón', '83134'),
('Azteca', '91', 'Pachuca', '83135'),
('5 de Febrero', '64', 'Mazatlán', '83136'),
('Del Río', '18', 'Culiacán', '83137'),
('Parque', '30', 'Hermosillo', '83138'),
('5 de Febrero', '15', 'Querétaro', '83139'); 

-- Insertar sucursales
INSERT INTO sucursal(domicilio_id, nombre) VALUES 
((SELECT id FROM domicilio_sucursal WHERE id=1), 'Ley 57'),
((SELECT id FROM domicilio_sucursal WHERE id=2), 'Santa María'),
((SELECT id FROM domicilio_sucursal WHERE id=3), 'Guadalupe'),
((SELECT id FROM domicilio_sucursal WHERE id=4), 'Centro'),
((SELECT id FROM domicilio_sucursal WHERE id=5), 'San Juan'),
((SELECT id FROM domicilio_sucursal WHERE id=6), 'Santa Isabel'),
((SELECT id FROM domicilio_sucursal WHERE id=7), 'Roma'),
((SELECT id FROM domicilio_sucursal WHERE id=8), 'Guadalajara'),
((SELECT id FROM domicilio_sucursal WHERE id=9), 'Tlalpan'),
((SELECT id FROM domicilio_sucursal WHERE id=10), 'Monterrey'),
((SELECT id FROM domicilio_sucursal WHERE id=11), 'Polanco'),
((SELECT id FROM domicilio_sucursal WHERE id=12), 'Chimalhuacán'),
((SELECT id FROM domicilio_sucursal WHERE id=13), 'Querétaro I'),  
((SELECT id FROM domicilio_sucursal WHERE id=14), 'La Condesa'),
((SELECT id FROM domicilio_sucursal WHERE id=15), 'Iztacalco'),
((SELECT id FROM domicilio_sucursal WHERE id=16), 'Coyoacán'),
((SELECT id FROM domicilio_sucursal WHERE id=17), 'Juárez'),
((SELECT id FROM domicilio_sucursal WHERE id=18), 'Mérida'),
((SELECT id FROM domicilio_sucursal WHERE id=19), 'Veracruz'),
((SELECT id FROM domicilio_sucursal WHERE id=20), 'Guanajuato'),
((SELECT id FROM domicilio_sucursal WHERE id=21), 'Puebla'),
((SELECT id FROM domicilio_sucursal WHERE id=22), 'San Ángel'),
((SELECT id FROM domicilio_sucursal WHERE id=23), 'Tepito'),
((SELECT id FROM domicilio_sucursal WHERE id=24), 'Benito Juárez'),
((SELECT id FROM domicilio_sucursal WHERE id=25), 'Tlajomulco'),
((SELECT id FROM domicilio_sucursal WHERE id=26), 'Querétaro II'),  
((SELECT id FROM domicilio_sucursal WHERE id=27), 'Lomas'),
((SELECT id FROM domicilio_sucursal WHERE id=28), 'Naucalpan'),
((SELECT id FROM domicilio_sucursal WHERE id=29), 'Santiago'),
((SELECT id FROM domicilio_sucursal WHERE id=30), 'Hidalgo'),
((SELECT id FROM domicilio_sucursal WHERE id=31), 'San Luis Potosí'),
((SELECT id FROM domicilio_sucursal WHERE id=32), 'Nayarit'),
((SELECT id FROM domicilio_sucursal WHERE id=33), 'San José'),
((SELECT id FROM domicilio_sucursal WHERE id=34), 'Toluca'),
((SELECT id FROM domicilio_sucursal WHERE id=35), 'Durango'),
((SELECT id FROM domicilio_sucursal WHERE id=36), 'Cdmx'),
((SELECT id FROM domicilio_sucursal WHERE id=37), 'Colima'),
((SELECT id FROM domicilio_sucursal WHERE id=38), 'San Felipe'),
((SELECT id FROM domicilio_sucursal WHERE id=39), 'Torreón'),
((SELECT id FROM domicilio_sucursal WHERE id=40), 'Pachuca');
